name       : caja-dropbox
version    : 1.20.0
release    : 4
source     :
    - https://pub.mate-desktop.org/releases/1.20/caja-dropbox-1.20.0.tar.xz : 721f2c7df9f27c63438bfdd9ef26d5402b30eca497ae73b8771a1a5ba2635876
license    :
    - CC-BY-ND-3.0
    - GPL-3.0
summary    : Dropbox linux client
component  : desktop.mate
description: |
    Dropbox Linux client for the MATE Desktop
builddeps  :
    - pkgconfig(libcaja-extension)
    - pkgconfig(glib-2.0)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(pygobject-2.0)
    - pkgconfig(pycairo)
    - python-docutils
rundeps    :
    - python-gobject2
    - python-pygpgme
    - python-gtk2
    - python-cairo
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
