name       : caja-dropbox
version    : 1.22.0
release    : 5
source     :
    - https://github.com/mate-desktop//caja-dropbox/archive/v1.22.0.tar.gz : 400c6b9bc23ed873721d1885a4eeb3197b461372a01c270a28af4dfcf875239d
license    :
    - CC-BY-ND-3.0
    - GPL-3.0-or-later
summary    : Dropbox linux client
component  : desktop.mate
description: |
    Dropbox Linux client for the MATE Desktop
builddeps  :
    - pkgconfig(libcaja-extension)
    - pkgconfig(glib-2.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(pycairo)
    - python-docutils
    - mate-common
rundeps    :
    - python-gpg
    - python3-cairo
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
