name       : caja-dropbox
version    : 1.24.0
release    : 8
source     :
    - https://github.com/mate-desktop/caja-dropbox/archive/v1.24.0.tar.gz : f76c9effccf7f36650cda9e82ad1c581a4535d7b9da05dd99e767699c46dc311
license    :
    - CC-BY-ND-3.0
    - GPL-3.0-or-later
summary    : Dropbox linux client
component  : desktop.mate
description: |
    Dropbox Linux client for the MATE Desktop
builddeps  :
    - pkgconfig(libcaja-extension)
    - pkgconfig(glib-2.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(pycairo)
    - python-docutils
    - mate-common
rundeps    :
    - python-gpg
    - python3-cairo
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
