name       : caja-dropbox
version    : 1.22.1
release    : 7
source     :
    - https://github.com/mate-desktop/caja-dropbox/archive/v1.22.1.tar.gz : 389e172a282054d5486f57315b25fa62544bcd0c9d46ea6ddab0913f88a884a9
license    :
    - CC-BY-ND-3.0
    - GPL-3.0-or-later
summary    : Dropbox linux client
component  : desktop.mate
description: |
    Dropbox Linux client for the MATE Desktop
builddeps  :
    - pkgconfig(libcaja-extension)
    - pkgconfig(glib-2.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(pycairo)
    - python-docutils
    - mate-common
rundeps    :
    - python-gpg
    - python3-cairo
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
