name       : caja-dropbox
version    : 1.26.0
release    : 10
source     :
    - https://github.com/mate-desktop/caja-dropbox/releases/download/v1.26.0/caja-dropbox-1.26.0.tar.xz : 9693d0c3426822d5b549e2241cd2b8a0ed552d4eebf2c87fa522e82b3fc8849b
license    :
    - CC-BY-ND-3.0
    - GPL-3.0-or-later
summary    : Dropbox linux client
component  : desktop.mate
description: |
    Dropbox Linux client for the MATE Desktop
builddeps  :
    - pkgconfig(libcaja-extension)
    - pkgconfig(glib-2.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(pycairo)
    - python-docutils
rundeps    :
    - python-gpg
    - python3-cairo
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
